In [1]:
import torch


<h1>Initislizing Tensor<h1>

In [8]:
device = "cuda" if torch.cuda.is_available else "cpu"

In [9]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device)

In [10]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [11]:
print(my_tensor.dtype)

torch.float32


In [12]:
print(my_tensor.device)

cuda:0


In [14]:
print(my_tensor.shape)

torch.Size([2, 3])


<h1>other initialization methods<h1>

In [15]:
x = torch.empty(size = (3,3))

In [17]:
x1 = torch.zeros((3,3))

In [18]:
print(x,x1)

tensor([[-1.8733e-36,  3.0663e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  6.4460e-44],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [19]:
y=torch.rand((3,3))

In [20]:
print(y)

tensor([[0.3621, 0.5238, 0.9975],
        [0.8192, 0.8260, 0.5082],
        [0.6105, 0.0677, 0.2855]])


In [21]:
y=torch.ones((3,3))

In [22]:
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [24]:
y=torch.eye(3)

In [25]:
print(y)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [26]:
y=torch.arange(0,10,2)

In [27]:
print(y)

tensor([0, 2, 4, 6, 8])


In [28]:
x = torch.linspace(start=0.1,end=1,steps=10)

In [29]:
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [30]:
y = torch.empty(size=(3,3)).normal_(mean=0,std=1)

In [31]:
print(y)

tensor([[ 0.1347, -0.4193,  0.3369],
        [-0.2618, -0.4524, -0.9609],
        [-0.3382, -1.0275, -0.7719]])


In [32]:
x=torch.empty(size=(1,5)).uniform_(0,1)

In [33]:
print(x)

tensor([[0.9996, 0.4878, 0.3078, 0.8140, 0.3726]])


In [34]:
x= torch.diag(torch.ones(3))

In [35]:
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


<h1>Initialize and convert to other type (int,float,double)<h1>

In [36]:
tensor=torch.arange(4)

In [37]:
tensor

tensor([0, 1, 2, 3])

In [38]:
tensor.dtype

torch.int64

In [39]:
tensor.bool()

tensor([False,  True,  True,  True])

In [40]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [41]:
tensor.long()

tensor([0, 1, 2, 3])

In [42]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [43]:
tensor.float()

tensor([0., 1., 2., 3.])

In [44]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [45]:
import numpy as np

In [46]:
np_array = np.array([[1,2,3],[4,5,6]])

In [48]:
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
torch_array=torch.from_numpy(np_array)

In [49]:
torch_array

tensor([[1, 2, 3],
        [4, 5, 6]])

In [51]:
np_array_back = torch_array.numpy()

In [52]:
np_array_back

array([[1, 2, 3],
       [4, 5, 6]])

<h1> Tensor math and comparison operators <h1>

In [53]:
x = torch.tensor([1,2,3])
y=torch.tensor([9,8,7])

<h1>Addition<h1>


In [55]:
z1 = torch.empty(3)
torch.add(x,y,out=z1)

tensor([10., 10., 10.])

In [56]:
z2=torch.add(x,y)

In [57]:
z2

tensor([10, 10, 10])

In [58]:
z=x+y

In [59]:
z

tensor([10, 10, 10])

<h1>Subtraction<h1>

In [61]:
z = x-y
z

tensor([-8, -6, -4])

In [62]:
#division
z=torch.true_divide(x,y)
z

tensor([0.1111, 0.2500, 0.4286])

In [63]:
#inplace operation
t=torch.zeros(3)
t.add_(x)
t

tensor([1., 2., 3.])

In [65]:
#exponentiation
z=x.pow(2)
z

tensor([1, 4, 9])

In [67]:
#simple comparison
z= x>0
z
z=x<=0
z

tensor([False, False, False])

In [69]:
#matrix multiplication
x1 = torch.rand((2,5))
x2= torch.rand((5,3))
x3=torch.mm(x1,x2)
x4=x1.mm(x2)
print(x3,x4)

tensor([[1.0627, 0.6837, 1.7649],
        [0.8248, 0.8758, 2.3898]]) tensor([[1.0627, 0.6837, 1.7649],
        [0.8248, 0.8758, 2.3898]])


In [70]:
#matrix exponentiation
matrix_exp = torch.rand((5,5))
matrix_exp.matrix_power(3)

tensor([[1.9381, 1.4151, 3.1426, 1.5073, 3.8365],
        [1.5082, 1.1962, 2.4333, 1.2185, 3.0812],
        [2.0619, 1.5990, 3.3471, 1.6263, 4.2589],
        [1.9010, 1.3469, 3.1649, 1.5692, 3.8282],
        [1.2762, 0.9322, 2.1469, 1.0404, 2.7081]])

In [71]:
#elementwise
z = x*y
z

tensor([ 9, 16, 21])

In [73]:
#dot product
z= torch.dot(x,y)
z

tensor(46)

In [75]:
#batch matrix multiplicatiom
batch=32
n=10
m=20
p=30

tensor1=torch.rand((batch,n,m))
tensor2 =torch.rand((batch,m,p))
out_bmm = torch.bmm(tensor1,tensor2) #(n,p)
out_bmm

tensor([[[5.9561, 3.6617, 5.0150,  ..., 5.1876, 3.6784, 3.9004],
         [4.1467, 3.3403, 4.5206,  ..., 4.4011, 3.7219, 3.9391],
         [6.4890, 4.0393, 5.6008,  ..., 5.3567, 4.4072, 4.7923],
         ...,
         [5.4165, 3.9443, 5.4644,  ..., 4.7115, 4.2237, 4.1800],
         [6.5085, 5.1261, 5.9530,  ..., 5.4251, 4.8398, 5.5755],
         [6.6358, 5.3675, 5.9274,  ..., 6.1584, 4.8878, 4.5485]],

        [[4.9865, 6.1510, 5.2473,  ..., 4.4559, 4.9457, 4.6363],
         [4.4854, 6.1013, 4.3341,  ..., 4.0221, 4.7060, 5.2591],
         [5.2199, 6.4320, 4.4818,  ..., 5.5244, 4.8550, 4.5209],
         ...,
         [4.8582, 6.1848, 4.9578,  ..., 4.9221, 5.2907, 5.2456],
         [4.6186, 6.1119, 5.2314,  ..., 4.5715, 4.9266, 5.6140],
         [4.2049, 5.9179, 3.4702,  ..., 4.3226, 5.1882, 3.3774]],

        [[5.5536, 5.6678, 6.4006,  ..., 6.4665, 6.2110, 6.4386],
         [3.9688, 4.3639, 4.6895,  ..., 5.0103, 4.4729, 4.7988],
         [4.8453, 5.2381, 5.6271,  ..., 6.0755, 5.0490, 6.

In [ ]:
#example of broadcasting

