<a href="https://colab.research.google.com/github/Hemant-ML/Pytorch-Master/blob/main/Day_1_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Importing libraries</h1>

In [24]:
import torch
import numpy as np
import matplotlib.pyplot as plt

torch.manual_seed(123)

<h1>Initializing Tensor<h1>

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [3]:
my_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]],dtype=torch.float32,device=device)

In [4]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], device='cuda:0')


In [5]:
print(my_tensor.dtype)

torch.float32


In [6]:
print(my_tensor.device)

cuda:0


In [7]:
print(my_tensor.shape)

torch.Size([3, 3])


<h1>other initialization methods<h1>

In [8]:
x = torch.empty(3,3)

In [9]:
x1 = torch.zeros((3,3))

In [10]:
print(x,x1)

tensor([[-3.7420e+33,  3.0613e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  0.0000e+00],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [14]:
#number taken from normal distribution. By default mean=0 and std=1
y=torch.randn(3,3)
y

tensor([[-0.4015, -0.7291, -0.1218],
        [-0.4796, -0.5166, -0.3107],
        [ 0.2057,  0.9657,  0.7057]])

In [15]:
#no taken from uniform disstribution [0,1]
y1=torch.rand(3,3)
y1

tensor([[0.1459, 0.0969, 0.7076],
        [0.5112, 0.7050, 0.0114],
        [0.4702, 0.8526, 0.7320]])

In [16]:
y= torch.ones_like(y1)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
y=torch.eye(3)
y

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
#torch.arange(start,end,step_size)
y=torch.arange(0,10,2)
y

tensor([0, 2, 4, 6, 8])

In [19]:

x = torch.linspace(start=0.1,end=1,steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [28]:
y = torch.empty(3,3).normal_(mean=0,std=1)

y

tensor([[-0.4015, -0.7291, -0.1218],
        [-0.4796, -0.5166, -0.3107],
        [ 0.2057,  0.9657,  0.7057]])

In [29]:
x=torch.empty(1,5).uniform_(0,1)
x

tensor([[0.1459, 0.0969, 0.7076, 0.5112, 0.7050]])

In [30]:
x= torch.diag(y)
x

tensor([-0.4015, -0.5166,  0.7057])

<h1>Initialize and convert to other type (int,float,double)<h1>

In [31]:
tensor=torch.arange(4)

In [32]:
tensor

tensor([0, 1, 2, 3])

In [33]:
tensor.dtype

torch.int64

In [34]:
tensor.bool()

tensor([False,  True,  True,  True])

In [35]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [36]:
tensor.long()

tensor([0, 1, 2, 3])

In [37]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [38]:
tensor.float()

tensor([0., 1., 2., 3.])

In [39]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [40]:
np_array = np.array([[1,2,3],[4,5,6]])

In [41]:
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
torch_array=torch.from_numpy(np_array)

In [43]:
torch_array

tensor([[1, 2, 3],
        [4, 5, 6]])

In [44]:
np_array_back = torch_array.numpy()

In [45]:
np_array_back

array([[1, 2, 3],
       [4, 5, 6]])

<h1> Tensor math and comparison operators <h1>

In [46]:
x = torch.tensor([1,2,3])
y=torch.tensor([9,8,7])

<h1>Addition<h1>


In [47]:
z1 = torch.empty(3)
print(torch.add(x,y,out=z1),x+y,x.add(y),torch.add(x,y))

tensor([10., 10., 10.]) tensor([10, 10, 10]) tensor([10, 10, 10]) tensor([10, 10, 10])


<h1>Subtraction<h1>

In [48]:
z = x-y
z

tensor([-8, -6, -4])

In [50]:
#division
z=torch.true_divide(y,x)
z

tensor([9.0000, 4.0000, 2.3333])

In [52]:
#wherever _ there is inplace operation
t=torch.zeros(3)
t.add_(x)
t

tensor([1., 2., 3.])

In [53]:
#exponentiation
z=x.pow(2)
z

tensor([1, 4, 9])

In [54]:
#simple comparison
z= x>0
print(z)
z=x<=0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [56]:
#matrix multiplication
x1 = torch.rand((5,2))
x2= torch.rand((5,3))
x3=torch.mm(x1.T,x2)
x4=x1.T.mm(x2)
print(x3,x4)

tensor([[2.3269, 1.7523, 1.4526],
        [1.5877, 1.5875, 0.9443]]) tensor([[2.3269, 1.7523, 1.4526],
        [1.5877, 1.5875, 0.9443]])


In [57]:
#matrix exponentiation
matrix_exp = torch.rand((5,5))
matrix_exp.matrix_power(3)

tensor([[4.1573, 3.2568, 3.3922, 2.0159, 3.3206],
        [2.3992, 1.8879, 1.9911, 1.1633, 1.9319],
        [3.1266, 2.3969, 2.5419, 1.5334, 2.5542],
        [3.6363, 2.7914, 2.8935, 1.7815, 2.8824],
        [1.8266, 1.4077, 1.4851, 0.9094, 1.4860]])

In [58]:
#elementwise
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])
z = x*y
z

tensor([ 4, 10, 18])

In [59]:
#dot product
z= torch.dot(x,y)
z

tensor(32)

In [60]:
#batch matrix multiplicatiom
batch=32
n=10
m=20
p=30

tensor1=torch.randn((batch,n,m))
tensor2=torch.randn((batch,m,p)) 
output=tensor1.bmm(tensor2)
output.size()

torch.Size([32, 10, 30])

In [61]:
#example of broadcasting
x1=torch.rand((5,5))
x2=torch.rand((1,5))
x3=x1-x2
print(x3)




tensor([[-0.1071, -0.0019, -0.2777,  0.0714, -0.1623],
        [-0.3697,  0.0799, -0.8669,  0.5600, -0.6555],
        [-0.0863, -0.1528, -0.5131,  0.2667, -0.2366],
        [-0.3320, -0.4105, -0.7233,  0.4484, -0.1834],
        [-0.4774, -0.6249, -0.9174, -0.0964, -0.2323]])


In [62]:
print(x1*x2)

tensor([[0.6500, 0.4455, 0.7136, 0.0918, 0.4919],
        [0.4237, 0.5002, 0.1273, 0.2235, 0.1036],
        [0.6679, 0.3447, 0.4793, 0.1445, 0.4334],
        [0.4562, 0.1724, 0.2702, 0.1934, 0.4753],
        [0.3310, 0.0291, 0.0771, 0.0466, 0.4368]])


In [63]:
#---------------------Other_tensor_operation-----------------------
x=torch.tensor([[1,2,3,4],[5,6,7,8]])
y=x
print(f"Column wise sum: \n {torch.sum(x,dim=0)} ")
print(f"row wise sum \n  {torch.sum(x,dim=1)}")
value,index=torch.min(x,dim=0)
print(value)
value,index=torch.max(x,dim=1)
print(value)
index=torch.argmax(x,dim=0)
print(index)
index=torch.argmin(x,dim=1)
print(index)
print(torch.mean(x.float(),dim=0))
print(torch.eq(x,y))
value,index=torch.sort(x,dim=0,descending=True)
print(value)
print(torch.clamp(x,min=2,max=5)) #you can use it make your RELU

Column wise sum: 
 tensor([ 6,  8, 10, 12]) 
row wise sum 
  tensor([10, 26])
tensor([1, 2, 3, 4])
tensor([4, 8])
tensor([1, 1, 1, 1])
tensor([0, 0])
tensor([3., 4., 5., 6.])
tensor([[True, True, True, True],
        [True, True, True, True]])
tensor([[5, 6, 7, 8],
        [1, 2, 3, 4]])
tensor([[2, 2, 3, 4],
        [5, 5, 5, 5]])


<h1>-----------tensor_indexing-------------</h1>

In [64]:
batch_size = 10
feature=25
z = torch.rand((batch_size,feature))

In [65]:
print(z[0,:].shape)  # x[0,:]

torch.Size([25])


In [66]:
#print first feature
print(z[:,0].shape)

torch.Size([10])


In [67]:
#get 3rd ex up to 10 feature
print(z[2,0:10])

tensor([0.9003, 0.0411, 0.3458, 0.8994, 0.8810, 0.5502, 0.7342, 0.4790, 0.9703,
        0.3160])


In [68]:
#you can assign value to the tensor
z[0,0]=100
print(z[0,0])

tensor(100.)


In [69]:
# Fancy Indexing
x=torch.arange(10)
indices = [2,5,8]
print(x[indices])
x=torch.rand((3,5))
rows = torch.tensor([1,0])
cols=torch.tensor([4,0])
print(x[rows,cols])

tensor([2, 5, 8])
tensor([0.8499, 0.2202])


In [70]:
# more advance indexing
x=torch.arange(10)
print(x[(x<2) | (x>8)])

tensor([0, 1, 9])


In [71]:
print(x[x.remainder(2)==0])

tensor([0, 2, 4, 6, 8])


In [74]:
#useful Operation
print(torch.where(x>5,x,x*2))
print(torch.tensor([0,0,1,1,2,3,3]).unique())
print(x.ndimension())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3])
1


In [75]:
# returns total number of input tensor
print(x.numel())

10


<h1>-------------reshaping matrix--------</h1>

In [76]:
x = torch.arange(9)
x_3x3=x.view(3,3) #need contiguous memory
print(x_3x3)
x_3x3=x.reshape(3,3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [77]:
y=x_3x3.t()
y.flatten()

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [78]:
x1 = torch.rand((2,5))
x2= torch.rand((2,5))
print(torch.cat((x1,x2),dim=0).shape) #vertically stack
print(torch.cat((x1,x2),dim=1).shape) #h stack

torch.Size([4, 5])
torch.Size([2, 10])


In [79]:
batch = 64
x =  torch.rand((batch,2,5))
z =x.view(batch,-1)
print(z.shape)

torch.Size([64, 10])


In [80]:
#switch axis while keeping batch
z= x.permute(0,2,1)
print(z.shape)

torch.Size([64, 5, 2])


In [81]:
# torch.unsqueeze() returns a new tensor with a dimension of size one inserted at the specified position.
x = torch.arange(10)  #[0,1,2,...,9]
print(x.unsqueeze(0)) #[1,10]
print(x.unsqueeze(1))  #[10,1]

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [82]:
!nvidia-smi


Sat May 15 19:26:22 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P0    35W / 250W |    897MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------