<h1>Importing libraries</h1>

In [102]:
import torch
torch.manual_seed(0)

<h1>Initializing Tensor<h1>

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
my_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]],dtype=torch.float32,device=device)

In [7]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [8]:
print(my_tensor.dtype)

torch.float32


In [9]:
print(my_tensor.device)

cpu


In [10]:
print(my_tensor.shape)

torch.Size([3, 3])


<h1>other initialization methods<h1>

In [11]:
x = torch.empty(3,3)

In [12]:
x1 = torch.zeros((3,3))

In [13]:
print(x,x1)

tensor([[0.0000e+00, 0.0000e+00, 4.2100e+21],
        [8.3567e+20, 2.7626e-06, 2.0430e+20],
        [5.3182e+22, 1.0570e+21, 6.6457e-07]]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [23]:
#number taken from normal distribution. By default mean=0 and std=1
y=torch.randn(3,3)
y

tensor([[-0.9122, -1.0258,  2.2417],
        [-0.5790, -0.2617,  0.2183],
        [ 1.0090,  0.9478, -0.0375]])

In [26]:
#no taken from uniform disstribution [0,1]
y1=torch.rand(3,3)
y1

tensor([[0.7435, 0.8612, 0.7689],
        [0.8378, 0.7396, 0.6955],
        [0.1868, 0.7715, 0.6355]])

In [27]:
y= torch.ones_like(y1)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
y=torch.eye(3)
y

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [30]:
#torch.arange(start,end,step_size)
y=torch.arange(0,10,2)
y

tensor([0, 2, 4, 6, 8])

In [31]:
x = torch.linspace(start=0.1,end=1,steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [37]:
y = torch.empty(3,3).normal_(mean=0,std=1)

y

tensor([[ 0.1408,  1.5271,  0.4606],
        [-1.1995, -0.1804, -0.4344],
        [ 1.4156, -1.2272, -0.4847]])

In [38]:
x=torch.empty(1,5).uniform_(0,1)
x

tensor([[0.3191, 0.0241, 0.4423, 0.4521, 0.0728]])

In [44]:
x= torch.diag(y)
x

tensor([ 0.1408, -0.1804, -0.4847])

<h1>Initialize and convert to other type (int,float,double)<h1>

In [45]:
tensor=torch.arange(4)

In [46]:
tensor

tensor([0, 1, 2, 3])

In [47]:
tensor.dtype

torch.int64

In [48]:
tensor.bool()

tensor([False,  True,  True,  True])

In [49]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [50]:
tensor.long()

tensor([0, 1, 2, 3])

In [51]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [52]:
tensor.float()

tensor([0., 1., 2., 3.])

In [35]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [53]:
import numpy as np

In [54]:
np_array = np.array([[1,2,3],[4,5,6]])

In [55]:
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
torch_array=torch.from_numpy(np_array)

In [57]:
torch_array

tensor([[1, 2, 3],
        [4, 5, 6]])

In [58]:
np_array_back = torch_array.numpy()

In [59]:
np_array_back

array([[1, 2, 3],
       [4, 5, 6]])

<h1> Tensor math and comparison operators <h1>

In [60]:
x = torch.tensor([1,2,3])
y=torch.tensor([9,8,7])

<h1>Addition<h1>


In [64]:
z1 = torch.empty(3)
print(torch.add(x,y,out=z1),x+y,x.add(y),torch.add(x,y))

tensor([10., 10., 10.]) tensor([10, 10, 10]) tensor([10, 10, 10]) tensor([10, 10, 10])


<h1>Subtraction<h1>

In [65]:
z = x-y
z

tensor([-8, -6, -4])

In [66]:
#division
z=torch.true_divide(y,x)
z

tensor([9.0000, 4.0000, 2.3333])

In [67]:
#wherever _ there is inplace operation
t=torch.zeros(3)
t.add_(x)
t

tensor([1., 2., 3.])

In [68]:
#exponentiation
z=x.pow(2)
z

tensor([1, 4, 9])

In [69]:
#simple comparison
z= x>0
print(z)
z=x<=0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [71]:
#matrix multiplication
x1 = torch.rand((5,2))
x2= torch.rand((5,3))
x3=torch.mm(x1.T,x2)
x4=x1.T.mm(x2)
print(x3,x4)

tensor([[1.5722, 1.6630, 1.2291],
        [1.5595, 1.2148, 1.4974]]) tensor([[1.5722, 1.6630, 1.2291],
        [1.5595, 1.2148, 1.4974]])


In [72]:
#matrix exponentiation
matrix_exp = torch.rand((5,5))
matrix_exp.matrix_power(3)

tensor([[1.0263, 1.5631, 1.4491, 1.9820, 1.4090],
        [2.4208, 4.0263, 4.0632, 5.5037, 3.8877],
        [1.7967, 3.0177, 3.0748, 4.0187, 2.9044],
        [2.0915, 3.7480, 3.6286, 5.1722, 3.6209],
        [1.7360, 2.9036, 2.8044, 3.9306, 2.7381]])

In [73]:
#elementwise
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])
z = x*y
z

tensor([ 4, 10, 18])

In [74]:
#dot product
z= torch.dot(x,y)
z

tensor(32)

In [80]:
#batch matrix multiplicatiom
batch=32
n=10
m=20
p=30

tensor1=torch.randn((batch,n,m))
tensor2=torch.randn((batch,m,p)) 
output=tensor1.bmm(tensor2)
output.size()

torch.Size([32, 10, 30])

In [81]:
#example of broadcasting
x1=torch.rand((5,5))
x2=torch.rand((1,5))
x3=x1-x2
print(x3)




tensor([[-0.3206,  0.0452,  0.1680, -0.7466,  0.4358],
        [-0.0065, -0.1629, -0.3099, -0.2204,  0.6772],
        [-0.5831, -0.1567,  0.4075, -0.7476,  0.4544],
        [-0.0101,  0.5522,  0.3690, -0.6073,  0.4725],
        [-0.5891,  0.4392, -0.2902, -0.7960,  0.5015]])


In [82]:
print(x1*x2)

tensor([[0.4325, 0.0793, 0.4258, 0.2082, 0.2146],
        [0.6955, 0.0252, 0.1515, 0.7148, 0.2855],
        [0.2128, 0.0268, 0.5633, 0.2072, 0.2200],
        [0.6924, 0.2111, 0.5412, 0.3423, 0.2254],
        [0.2077, 0.1817, 0.1629, 0.1606, 0.2339]])


In [87]:
#---------------------Other_tensor_operation-----------------------
x=torch.tensor([[1,2,3,4],[5,6,7,8]])
y=x
print(f"Column wise sum: \n {torch.sum(x,dim=0)} ")
print(f"row wise sum \n  {torch.sum(x,dim=1)}")
value,index=torch.min(x,dim=0)
print(value)
value,index=torch.max(x,dim=1)
print(value)
index=torch.argmax(x,dim=0)
print(index)
index=torch.argmin(x,dim=1)
print(index)
print(torch.mean(x.float(),dim=0))
print(torch.eq(x,y))
value,index=torch.sort(x,dim=0,descending=True)
print(value)
print(torch.clamp(x,min=2,max=5))

Column wise sum: 
 tensor([ 6,  8, 10, 12]) 
row wise sum 
  tensor([10, 26])
tensor([1, 2, 3, 4])
tensor([4, 8])
tensor([1, 1, 1, 1])
tensor([0, 0])
tensor([3., 4., 5., 6.])
tensor([[True, True, True, True],
        [True, True, True, True]])
tensor([[5, 6, 7, 8],
        [1, 2, 3, 4]])
tensor([[2, 2, 3, 4],
        [5, 5, 5, 5]])


<h1>-----------tensor_indexing-------------</h1>

In [88]:
batch_size = 10
feature=25
z = torch.rand((batch_size,feature))

In [94]:
print(z[0,:].shape)  # x[0,:]

torch.Size([25])


In [95]:
#print first feature
print(z[:,0].shape)

torch.Size([10])


In [96]:
#get 3rd ex up to 10 feature
print(z[2,0:10])

tensor([0.3762, 0.0979, 0.5085, 0.5723, 0.9077, 0.0778, 0.6724, 0.1895, 0.4811,
        0.3119])


In [97]:
#you can assign value to the tensor
z[0,0]=100
print(z[0,0])

tensor(100.)


In [104]:
# Fancy Indexing
x=torch.arange(10)
indices = [2,5,8]
print(x[indices])
x=torch.rand((3,5))
rows = torch.tensor([1,0])
cols=torch.tensor([4,0])
print(x[rows,cols])

tensor([2, 5, 8])
tensor([0.4194, 0.5185])


In [106]:
# more advance indexing
x=torch.arange(10)
print(x[(x<2) | (x>8)])

tensor([0, 1, 9])


In [107]:
print(x[x.remainder(2)==0])

tensor([0, 2, 4, 6, 8])


In [111]:
#useful Operation
print(torch.where(x>5,x,x*2))
print(torch.tensor([0,0,1,1,2,3,3]).unique())
print(x.ndimension())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3])
1


In [112]:
# returns total number of input tensor
print(x.numel())

10


<h1>-------------reshaping matrix--------</h1>

In [113]:
x = torch.arange(9)
x_3x3=x.view(3,3) #need contiguous memory
print(x_3x3)
x_3x3=x.reshape(3,3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [114]:
y=x_3x3.t()
y.flatten()

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [116]:
x1 = torch.rand((2,5))
x2= torch.rand((2,5))
print(torch.cat((x1,x2),dim=0).shape) #vertically stack
print(torch.cat((x1,x2),dim=1).shape) #h stack

torch.Size([4, 5])
torch.Size([2, 10])


In [117]:
batch = 64
x =  torch.rand((batch,2,5))
z =x.view(batch,-1)
print(z.shape)

torch.Size([64, 10])


In [118]:
#switch axis while keeping batch
z= x.permute(0,2,1)
print(z.shape)

torch.Size([64, 5, 2])


In [119]:
# torch.unsqueeze() returns a new tensor with a dimension of size one inserted at the specified position.
x = torch.arange(10)  #[0,1,2,...,9]
print(x.unsqueeze(0)) #[1,10]
print(x.unsqueeze(1))  #[10,1]

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
