<a href="https://colab.research.google.com/github/Hemant-ML/Pytorch-Master/blob/main/Day_5_Fully_connected_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Importing libraries</h1>

In [98]:
import torch.nn as nn

In [108]:
x=torch.arange(50,dtype=torch.float32)
x=x.view(10,5)
x

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.]])

In [103]:
fc_layer = nn.Linear(in_features=5,out_features=3)

In [104]:
fc_layer.weight

Parameter containing:
tensor([[-0.2033, -0.1724,  0.1215, -0.4006, -0.3183],
        [ 0.3333, -0.1253,  0.1546,  0.3287, -0.3895],
        [-0.1346,  0.3263,  0.4181,  0.2494,  0.2668]], requires_grad=True)

In [106]:
fc_layer.bias

Parameter containing:
tensor([-0.1554,  0.1602,  0.2155], requires_grad=True)

In [107]:
A=fc_layer(x)
print(A)
print(A.size)

tensor([[ -2.5600,  -0.2276,   3.1931],
        [ -7.4260,   1.2817,   8.8227],
        [-12.2919,   2.7910,  14.4522],
        [-17.1579,   4.3003,  20.0818],
        [-22.0238,   5.8096,  25.7113],
        [-26.8898,   7.3189,  31.3409],
        [-31.7558,   8.8282,  36.9704],
        [-36.6217,  10.3375,  42.6000],
        [-41.4877,  11.8468,  48.2295],
        [-46.3536,  13.3561,  53.8591]], grad_fn=<AddmmBackward>)
<built-in method size of Tensor object at 0x7f9fb17df820>
