In [1]:
import torch


<h1>Initializing Tensor<h1>

In [61]:
device = "cuda" if torch.cuda.is_available else "cpu"

In [3]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device)

In [4]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [5]:
print(my_tensor.dtype)

torch.float32


In [6]:
print(my_tensor.device)

cuda:0


In [7]:
print(my_tensor.shape)

torch.Size([2, 3])


<h1>other initialization methods<h1>

In [8]:
x = torch.empty(size = (3,3))

In [9]:
x1 = torch.zeros((3,3))

In [10]:
print(x,x1)

tensor([[2.6450e-09, 3.0942e-41, 3.3631e-44],
        [0.0000e+00,        nan, 3.0941e-41],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [11]:
y=torch.rand((3,3))

In [12]:
print(y)

tensor([[0.3288, 0.7828, 0.6812],
        [0.2144, 0.9665, 0.8827],
        [0.0463, 0.3824, 0.9899]])


In [13]:
y=torch.ones((3,3))

In [14]:
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [15]:
y=torch.eye(3)

In [16]:
print(y)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [17]:
y=torch.arange(0,10,2)

In [18]:
print(y)

tensor([0, 2, 4, 6, 8])


In [19]:
x = torch.linspace(start=0.1,end=1,steps=10)

In [20]:
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [21]:
y = torch.empty(size=(3,3)).normal_(mean=0,std=1)

In [22]:
print(y)

tensor([[ 0.7018, -1.1102, -2.4992],
        [ 0.2305, -0.4899,  1.8335],
        [ 0.5406, -1.0167, -0.0726]])


In [23]:
x=torch.empty(size=(1,5)).uniform_(0,1)

In [24]:
print(x)

tensor([[0.9006, 0.2167, 0.2238, 0.1542, 0.7555]])


In [25]:
x= torch.diag(torch.ones(3))

In [26]:
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


<h1>Initialize and convert to other type (int,float,double)<h1>

In [27]:
tensor=torch.arange(4)

In [28]:
tensor

tensor([0, 1, 2, 3])

In [29]:
tensor.dtype

torch.int64

In [30]:
tensor.bool()

tensor([False,  True,  True,  True])

In [31]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [32]:
tensor.long()

tensor([0, 1, 2, 3])

In [33]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [34]:
tensor.float()

tensor([0., 1., 2., 3.])

In [35]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [36]:
import numpy as np

In [37]:
np_array = np.array([[1,2,3],[4,5,6]])

In [38]:
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
torch_array=torch.from_numpy(np_array)

In [40]:
torch_array

tensor([[1, 2, 3],
        [4, 5, 6]])

In [41]:
np_array_back = torch_array.numpy()

In [42]:
np_array_back

array([[1, 2, 3],
       [4, 5, 6]])

<h1> Tensor math and comparison operators <h1>

In [43]:
x = torch.tensor([1,2,3])
y=torch.tensor([9,8,7])

<h1>Addition<h1>


In [44]:
z1 = torch.empty(3)
torch.add(x,y,out=z1)

tensor([10., 10., 10.])

In [45]:
z2=torch.add(x,y)

In [46]:
z2

tensor([10, 10, 10])

In [47]:
z=x+y

In [48]:
z

tensor([10, 10, 10])

<h1>Subtraction<h1>

In [49]:
z = x-y
z

tensor([-8, -6, -4])

In [50]:
#division
z=torch.true_divide(x,y)
z

tensor([0.1111, 0.2500, 0.4286])

In [51]:
#inplace operation
t=torch.zeros(3)
t.add_(x)
t

tensor([1., 2., 3.])

In [52]:
#exponentiation
z=x.pow(2)
z

tensor([1, 4, 9])

In [53]:
#simple comparison
z= x>0
z
z=x<=0
z

tensor([False, False, False])

In [54]:
#matrix multiplication
x1 = torch.rand((2,5))
x2= torch.rand((5,3))
x3=torch.mm(x1,x2)
x4=x1.mm(x2)
print(x3,x4)

tensor([[1.1205, 1.2350, 0.8630],
        [0.9560, 1.2329, 0.7818]]) tensor([[1.1205, 1.2350, 0.8630],
        [0.9560, 1.2329, 0.7818]])


In [55]:
#matrix exponentiation
matrix_exp = torch.rand((5,5))
matrix_exp.matrix_power(3)

tensor([[2.6228, 4.0148, 4.0274, 5.0467, 3.6335],
        [1.1234, 1.7090, 1.7235, 2.1535, 1.4865],
        [2.6943, 4.1142, 4.1125, 5.1453, 3.7083],
        [2.4524, 3.7376, 3.8476, 4.7665, 3.2743],
        [1.2965, 2.0127, 1.8411, 2.4082, 2.0381]])

In [56]:
#elementwise
z = x*y
z

tensor([ 9, 16, 21])

In [57]:
#dot product
z= torch.dot(x,y)
z

tensor(46)

In [58]:
#batch matrix multiplicatiom
batch=32
n=10
m=20
p=30

tensor1=torch.rand((batch,n,m))
tensor2 =torch.rand((batch,m,p))
out_bmm = torch.bmm(tensor1,tensor2) #(n,p)
out_bmm

tensor([[[5.1547, 6.1685, 5.4458,  ..., 3.9173, 5.1661, 3.9763],
         [5.8688, 6.3839, 6.3506,  ..., 4.1184, 5.7413, 4.6787],
         [4.5241, 4.7302, 4.2720,  ..., 2.5839, 3.1229, 3.6298],
         ...,
         [5.6624, 5.4470, 5.3483,  ..., 4.3805, 3.9904, 4.3218],
         [4.2758, 4.9669, 5.1666,  ..., 3.9237, 4.7115, 4.5187],
         [5.7712, 5.6763, 5.6009,  ..., 4.6951, 4.3443, 5.6542]],

        [[4.8228, 4.5692, 3.4510,  ..., 4.4714, 4.4609, 4.9075],
         [6.5658, 5.3739, 4.4767,  ..., 5.1485, 6.5346, 7.0477],
         [4.6541, 5.0018, 3.1049,  ..., 4.3859, 4.2424, 5.0882],
         ...,
         [5.3366, 5.3971, 3.9449,  ..., 5.1791, 5.4910, 6.2391],
         [5.3829, 5.0954, 4.2485,  ..., 5.1393, 5.0397, 5.6445],
         [4.8028, 4.3808, 3.6138,  ..., 4.3202, 4.2196, 4.6441]],

        [[5.4277, 5.1204, 3.5601,  ..., 5.7230, 5.4279, 5.0155],
         [6.5057, 6.3444, 4.5111,  ..., 6.6467, 5.5804, 5.8242],
         [3.8889, 4.5608, 3.9389,  ..., 5.3523, 4.8677, 3.

In [62]:
#example of broadcasting
x1=torch.rand((5,5))
x2=torch.rand((1,5))
x3=x1-x2
print(x3)




tensor([[ 0.5505, -0.1457,  0.2037, -0.3779,  0.0759],
        [ 0.4556,  0.0691,  0.6525, -0.0155,  0.4704],
        [ 0.7610, -0.2725,  0.7563, -0.9349,  0.0860],
        [ 0.8018, -0.5027,  0.4831, -0.2680, -0.2130],
        [ 0.3822, -0.2593,  0.9038, -0.8848,  0.2676]])


In [65]:
print(x1*x2)

tensor([[0.0301, 0.3141, 0.0077, 0.5351, 0.2319],
        [0.0254, 0.4512, 0.0224, 0.8773, 0.4075],
        [0.0407, 0.2333, 0.0258, 0.0090, 0.2364],
        [0.0427, 0.0864, 0.0169, 0.6388, 0.1033],
        [0.0217, 0.2417, 0.0307, 0.0563, 0.3172]])


In [72]:
#---------------------Other_tensor_operation-----------------------
x=torch.tensor([[1,2,3,4],[5,6,7,8]])
y=x
print(torch.sum(x,dim=0))
print(torch.sum(x,dim=1))
value,index=torch.min(x,dim=0)
print(value)
value,index=torch.max(x,dim=1)
print(value)
index=torch.argmax(x,dim=0)
print(index)
index=torch.argmin(x,dim=1)
print(index)
print(torch.mean(x.float(),dim=0))
print(torch.eq(x,y))
value,index=torch.sort(x,dim=0,descending=True)
print(value)
print(torch.clamp(x,min=0,max=5))

tensor([ 6,  8, 10, 12])
tensor([10, 26])
tensor([1, 2, 3, 4])
tensor([4, 8])
tensor([1, 1, 1, 1])
tensor([0, 0])
tensor([3., 4., 5., 6.])
tensor([[True, True, True, True],
        [True, True, True, True]])
tensor([[5, 6, 7, 8],
        [1, 2, 3, 4]])
tensor([[1, 2, 3, 4],
        [5, 5, 5, 5]])


<h1>-----------tensor_indexing-------------</h1>

In [73]:
batch_size = 10
feature=25
z = torch.rand((batch_size,feature))

In [74]:
print(z[0].shape)  # x[0,:]

torch.Size([25])


In [75]:
#print first feature
print(z[:,0].shape)

torch.Size([10])


In [76]:
#get 3rd ex up to 10 feature
print(z[2,0:10])

tensor([0.1097, 0.7228, 0.8232, 0.9657, 0.8420, 0.2481, 0.8307, 0.8442, 0.6629,
        0.0557])


In [78]:
#you can assign value to the tensor
z[0,0]=100
print(z[0,0])

tensor(100.)


In [81]:
# Fancy Indexing
x=torch.arange(10)
indices = [2,5,8]
print(x[indices])
x=torch.rand((3,5))
rows = torch.tensor([1,0])
cols=torch.tensor([4,0])
print(x[rows,cols])

tensor([2, 5, 8])
tensor([0.2769, 0.5394])


In [85]:
# more advance indexing
x=torch.arange(10)
print(x[(x<2) | (x>8)])

tensor([0, 1, 9])


In [86]:
print(x[x.remainder(2)==0])

tensor([0, 2, 4, 6, 8])


In [88]:
#useful Operation
print(torch.where(x>5,x,x*2))
print(torch.tensor([0,0,1,1,2,3,3]).unique())
print(x.ndimension())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3])
1


In [89]:
print(x.numel())

10


<h1>-------------reshaping matrix--------</h1>

In [90]:
x = torch.arange(9)
x_3x3=x.view(3,3) #need contiguous memory
print(x_3x3)
x_3x3=x.reshape(3,3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [92]:
y=x_3x3.t()
y.flatten()

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [94]:
x1 = torch.rand((2,5))
x2= torch.rand((2,5))
print(torch.cat((x1,x2),dim=0).shape) #vertically stack
print(torch.cat((x1,x2),dim=1).shape) #h stack

torch.Size([4, 5])
torch.Size([2, 10])


In [95]:
batch = 64
x =  torch.rand((batch,2,5))
z =x.view(batch,-1)
print(z.shape)

torch.Size([64, 10])


In [96]:
#switch axis while keeping batch
z= x.permute(0,2,1)
print(z.shape)

torch.Size([64, 5, 2])


In [2]:
x = torch.arange(10)  #[0,1,2,...,9]
print(x.unsqueeze(0).shape) #[1,10]
print(x.unsqueeze(1).shape)  #[10,1]

torch.Size([1, 10])
torch.Size([10, 1])
