<a href="https://colab.research.google.com/github/Hemant-ML/Pytorch-Master/blob/main/Day_1_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Importing libraries</h1>

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

torch.manual_seed(123)

<h1>Initializing Tensor<h1>

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [3]:
my_tensor = torch.tensor([[1.,2.,3.],[4.,5.,6.]],dtype=torch.float16,device=device)

In [4]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)


In [5]:
print(my_tensor.dtype)

torch.float16


In [9]:
print(my_tensor.device)

cpu


In [6]:
print(my_tensor.shape)

torch.Size([2, 3])


<h1>other initialization methods<h1>

In [8]:
x = torch.empty(3,3)
x

tensor([[-6.1409e+32,  4.5586e-41, -6.1414e+32],
        [ 4.5586e-41, -6.1767e+32,  4.5586e-41],
        [-6.1769e+32,  4.5586e-41, -6.0806e+32]])

In [9]:
x1=torch.zeros(3,3)

In [10]:
print(x1,x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[-6.1409e+32,  4.5586e-41, -6.1414e+32],
        [ 4.5586e-41, -6.1767e+32,  4.5586e-41],
        [-6.1769e+32,  4.5586e-41, -6.0806e+32]])


In [11]:
#number taken from normal distribution. By default mean=0 and std=1
y=torch.randn(3,3).normal_(mean=0,std=1)
y



tensor([[-0.1085,  0.2103, -0.3908],
        [ 0.2350,  0.6653,  0.3528],
        [ 0.9728, -0.0386, -0.8861]])

In [12]:
#no taken from uniform disstribution [0,1]
y1=torch.rand(3,3).uniform_(0,1)
y1

tensor([[0.5159, 0.4220, 0.5786],
        [0.9455, 0.8057, 0.6775],
        [0.6087, 0.6179, 0.6932]])

In [13]:
y= torch.ones_like(y1)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
y=torch.eye(3)
y

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [15]:
#torch.arange(start,end,step_size)
y=torch.arange(0,10,2)
y

tensor([0, 2, 4, 6, 8])

In [16]:

x = torch.linspace(start=0.1,end=1,steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [17]:
y = torch.empty(3,3).normal_(mean=0,std=1)

y

tensor([[-1.2157,  0.1295,  0.0967],
        [ 1.4086,  0.1915,  1.0041],
        [ 0.4198,  0.1882, -0.6040]])

In [18]:
x=torch.empty(1,5).uniform_(0,1)
x

tensor([[0.7076, 0.5112, 0.7050, 0.0114, 0.4702]])

In [19]:
x= torch.diag(y)
x

tensor([-1.2157,  0.1915, -0.6040])

<h1>Initialize and convert to other type (int,float,double)<h1>

In [20]:
tensor=torch.arange(4)

In [21]:
tensor

tensor([0, 1, 2, 3])

In [22]:
tensor.dtype

torch.int64

In [23]:
tensor.bool()

tensor([False,  True,  True,  True])

In [24]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [25]:
tensor.long()

tensor([0, 1, 2, 3])

In [26]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [27]:
tensor.float()

tensor([0., 1., 2., 3.])

In [28]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [29]:
np_array = np.array([[1,2,3],[4,5,6]])

In [30]:
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
torch_array=torch.from_numpy(np_array)

In [32]:
torch_array

tensor([[1, 2, 3],
        [4, 5, 6]])

In [33]:
np_array_back = torch_array.numpy()

In [35]:
np_array_back

array([[1, 2, 3],
       [4, 5, 6]])

<h1> Tensor math and comparison operators <h1>

In [36]:
x = torch.tensor([1,2,3])
y=torch.tensor([9,8,7])

<h1>Addition<h1>


In [37]:
z1 = torch.empty(3)
print(torch.add(x,y,out=z1),x+y,x.add(y),torch.add(x,y))

tensor([10., 10., 10.]) tensor([10, 10, 10]) tensor([10, 10, 10]) tensor([10, 10, 10])


<h1>Subtraction<h1>

In [38]:
z = x-y
z

tensor([-8, -6, -4])

In [39]:
#division
z=torch.true_divide(y,x)
z

tensor([9.0000, 4.0000, 2.3333])

In [40]:
#wherever _ there is inplace operation
t=torch.zeros(3)
t.add_(x)
t

tensor([1., 2., 3.])

In [41]:
#exponentiation
z=x.pow(2)
z

tensor([1, 4, 9])

In [42]:
#simple comparison
z= x>0
print(z)
z=x<=0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [43]:
#matrix multiplication
x1 = torch.rand((5,2))
x2= torch.rand((5,3))
x3=torch.mm(x1.T,x2)
x4=x1.T.mm(x2)
print(x3,x4)

tensor([[1.5696, 1.6052, 1.7650],
        [1.2835, 1.3122, 1.3597]]) tensor([[1.5696, 1.6052, 1.7650],
        [1.2835, 1.3122, 1.3597]])


In [44]:
#matrix exponentiation
matrix_exp = torch.rand((5,5))
matrix_exp.matrix_power(3)

tensor([[5.8805, 3.9918, 4.4332, 7.4143, 4.9280],
        [5.5381, 3.8280, 4.1221, 6.9377, 4.5196],
        [4.6329, 3.1718, 3.4700, 5.8261, 3.8677],
        [6.3804, 4.2244, 4.7419, 7.8303, 5.1014],
        [6.4983, 4.2490, 4.8388, 7.9231, 5.2394]])

In [45]:
#elementwise
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])
z = x*y
z

tensor([ 4, 10, 18])

In [46]:
#dot product
z= torch.dot(x,y)
z

tensor(32)

In [47]:
#batch matrix multiplicatiom
batch=32
n=10
m=20
p=30

tensor1=torch.randn((batch,n,m))
tensor2=torch.randn((batch,m,p)) 
output=tensor1.bmm(tensor2)
output.size()

torch.Size([32, 10, 30])

In [48]:
#example of broadcasting
x1=torch.rand((5,5))
x2=torch.rand((1,5))
x3=x1-x2
print(x3)




tensor([[-0.0283,  0.5813, -0.5292,  0.2077,  0.1392],
        [-0.4421,  0.1230, -0.4093, -0.0526, -0.2757],
        [-0.2908,  0.4442,  0.1383, -0.4419, -0.1286],
        [ 0.2827, -0.1451, -0.2562, -0.4626,  0.0873],
        [-0.1006,  0.4212,  0.0124,  0.2626, -0.0818]])


In [49]:
print(x1*x2)

tensor([[0.4942, 0.3143, 0.0598, 0.3440, 0.6642],
        [0.1973, 0.1581, 0.1347, 0.2160, 0.3537],
        [0.3059, 0.2675, 0.4769, 0.0246, 0.4638],
        [0.7172, 0.0667, 0.2304, 0.0143, 0.6253],
        [0.4423, 0.2597, 0.3982, 0.3710, 0.4988]])


In [50]:
#---------------------Other_tensor_operation-----------------------
x=torch.tensor([[1,2,3,4],[5,6,7,8]])
y=x
print(f"Column wise sum: \n {torch.sum(x,dim=0)} ")
print(f"row wise sum \n  {torch.sum(x,dim=1)}")
value,index=torch.min(x,dim=0)
print(value)
value,index=torch.max(x,dim=1)
print(value)
index=torch.argmax(x,dim=0)
print(index)
index=torch.argmin(x,dim=1)
print(index)
print(torch.mean(x.float(),dim=0))
print(torch.eq(x,y))
value,index=torch.sort(x,dim=0,descending=True)
print(value)
print(torch.clamp(x,min=2,max=5)) #you can use it make your RELU

Column wise sum: 
 tensor([ 6,  8, 10, 12]) 
row wise sum 
  tensor([10, 26])
tensor([1, 2, 3, 4])
tensor([4, 8])
tensor([1, 1, 1, 1])
tensor([0, 0])
tensor([3., 4., 5., 6.])
tensor([[True, True, True, True],
        [True, True, True, True]])
tensor([[5, 6, 7, 8],
        [1, 2, 3, 4]])
tensor([[2, 2, 3, 4],
        [5, 5, 5, 5]])


<h1>-----------tensor_indexing-------------</h1>

In [51]:
batch_size = 10
feature=25
z = torch.rand((batch_size,feature))

In [52]:
print(z[0,:].shape)  # x[0,:]

torch.Size([25])


In [53]:
#print first feature
print(z[:,0].shape)

torch.Size([10])


In [54]:
#get 3rd ex up to 10 feature
print(z[2,0:10])

tensor([0.8086, 0.7744, 0.4699, 0.1511, 0.9356, 0.7688, 0.6516, 0.0754, 0.3141,
        0.2464])


In [55]:
#you can assign value to the tensor
z[0,0]=100
print(z[0,0])

tensor(100.)


In [56]:
# Fancy Indexing
x=torch.arange(10)
indices = [2,5,8]
print(x[indices])
x=torch.rand((3,5))
rows = torch.tensor([1,0])
cols=torch.tensor([4,0])
print(x[rows,cols])

tensor([2, 5, 8])
tensor([0.1210, 0.1174])


In [57]:
# more advance indexing
x=torch.arange(10)
print(x[(x<2) | (x>8)])

tensor([0, 1, 9])


In [58]:
print(x[x.remainder(2)==0])

tensor([0, 2, 4, 6, 8])


In [59]:
#useful Operation
print(torch.where(x>5,x,x*2))
print(torch.tensor([0,0,1,1,2,3,3]).unique())
print(x.ndimension())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3])
1


In [ ]:
# returns total number of input tensor
print(x.numel())

10


<h1>-------------reshaping matrix--------</h1>

In [60]:
x = torch.arange(9)
x_3x3=x.view(3,3) #need contiguous memory
print(x_3x3)
x_3x3=x.reshape(3,3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [63]:
y=x_3x3.t()
y.flatten()

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [64]:
x1 = torch.rand((2,5))
x2= torch.rand((2,5))
print(torch.cat((x1,x2),dim=0).shape) #vertically stack
print(torch.cat((x1,x2),dim=1).shape) #h stack

torch.Size([4, 5])
torch.Size([2, 10])


In [65]:
batch = 64
x =  torch.rand((batch,2,5))
z =x.view(batch,-1)
print(z.shape)

torch.Size([64, 10])


In [ ]:
#switch axis while keeping batch
z= x.permute(0,2,1)
print(z.shape)

torch.Size([64, 5, 2])


In [66]:
# torch.unsqueeze() returns a new tensor with a dimension of size one inserted at the specified position.
x = torch.arange(10)  #[0,1,2,...,9]
print(x.unsqueeze(0)) #[1,10]
print(x.unsqueeze(1))  #[10,1]

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
