<a href="https://colab.research.google.com/github/Hemant-ML/Pytorch-Master/blob/main/Day_1_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Importing libraries</h1>

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

torch.manual_seed(123)

<h1>Initializing Tensor<h1>

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [3]:
my_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]],dtype=torch.float32,device=device)

In [4]:
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [5]:
print(my_tensor.dtype)

torch.float32


In [6]:
print(my_tensor.device)

cpu


In [9]:
print(my_tensor.shape)

torch.Size([3, 3])


<h1>other initialization methods<h1>

In [13]:
x = torch.empty(3,3)

In [14]:
x1 = torch.zeros((3,3))

In [15]:
print(x,x1)

tensor([[4.9684e-16, 3.0698e-41, 0.0000e+00],
        [0.0000e+00, 7.8473e-44, 0.0000e+00],
        [2.2421e-44, 2.2421e-44, 1.4013e-45]]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [23]:
#number taken from normal distribution. By default mean=0 and std=1
y=torch.randn(3,3).normal_(mean=0,std=1)
y


tensor([[ 0.9670,  1.0445,  1.3972],
        [-0.9484, -0.2061,  1.3361],
        [ 0.1918, -0.0500,  2.0325]])

In [25]:
#no taken from uniform disstribution [0,1]
y1=torch.rand(3,3).uniform_(0,1)
y1

tensor([[0.9308, 0.0890, 0.4759],
        [0.5104, 0.5840, 0.1227],
        [0.9587, 0.9914, 0.1547]])

In [26]:
y= torch.ones_like(y1)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
y=torch.eye(3)
y

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [28]:
#torch.arange(start,end,step_size)
y=torch.arange(0,10,2)
y

tensor([0, 2, 4, 6, 8])

In [29]:

x = torch.linspace(start=0.1,end=1,steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [30]:
y = torch.empty(3,3).normal_(mean=0,std=1)

y

tensor([[ 1.1383,  1.5213, -0.8358],
        [ 1.0691,  0.3342,  0.1524],
        [ 1.0854, -0.2531, -0.7194]])

In [31]:
x=torch.empty(1,5).uniform_(0,1)
x

tensor([[0.0532, 0.9964, 0.2377, 0.4616, 0.9079]])

In [32]:
x= torch.diag(y)
x

tensor([ 1.1383,  0.3342, -0.7194])

<h1>Initialize and convert to other type (int,float,double)<h1>

In [33]:
tensor=torch.arange(4)

In [34]:
tensor

tensor([0, 1, 2, 3])

In [35]:
tensor.dtype

torch.int64

In [36]:
tensor.bool()

tensor([False,  True,  True,  True])

In [37]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [38]:
tensor.long()

tensor([0, 1, 2, 3])

In [39]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [40]:
tensor.float()

tensor([0., 1., 2., 3.])

In [41]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [42]:
np_array = np.array([[1,2,3],[4,5,6]])

In [43]:
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
torch_array=torch.from_numpy(np_array)

In [45]:
torch_array

tensor([[1, 2, 3],
        [4, 5, 6]])

In [46]:
np_array_back = torch_array.numpy()

In [47]:
np_array_back

array([[1, 2, 3],
       [4, 5, 6]])

<h1> Tensor math and comparison operators <h1>

In [48]:
x = torch.tensor([1,2,3])
y=torch.tensor([9,8,7])

<h1>Addition<h1>


In [49]:
z1 = torch.empty(3)
print(torch.add(x,y,out=z1),x+y,x.add(y),torch.add(x,y))

tensor([10., 10., 10.]) tensor([10, 10, 10]) tensor([10, 10, 10]) tensor([10, 10, 10])


<h1>Subtraction<h1>

In [50]:
z = x-y
z

tensor([-8, -6, -4])

In [51]:
#division
z=torch.true_divide(y,x)
z

tensor([9.0000, 4.0000, 2.3333])

In [52]:
#wherever _ there is inplace operation
t=torch.zeros(3)
t.add_(x)
t

tensor([1., 2., 3.])

In [53]:
#exponentiation
z=x.pow(2)
z

tensor([1, 4, 9])

In [54]:
#simple comparison
z= x>0
print(z)
z=x<=0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [55]:
#matrix multiplication
x1 = torch.rand((5,2))
x2= torch.rand((5,3))
x3=torch.mm(x1.T,x2)
x4=x1.T.mm(x2)
print(x3,x4)

tensor([[1.9355, 1.6771, 1.2743],
        [1.1301, 1.2115, 1.0228]]) tensor([[1.9355, 1.6771, 1.2743],
        [1.1301, 1.2115, 1.0228]])


In [56]:
#matrix exponentiation
matrix_exp = torch.rand((5,5))
matrix_exp.matrix_power(3)

tensor([[3.1231, 3.7154, 5.0476, 3.8310, 2.5067],
        [2.0299, 2.2959, 3.1543, 2.3739, 1.6308],
        [3.0772, 3.3634, 4.8000, 3.5104, 2.5196],
        [2.7440, 3.2042, 4.6809, 3.3677, 2.3117],
        [2.6748, 3.0784, 4.1741, 3.1768, 2.1502]])

In [57]:
#elementwise
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,6])
z = x*y
z

tensor([ 4, 10, 18])

In [58]:
#dot product
z= torch.dot(x,y)
z

tensor(32)

In [60]:
#batch matrix multiplicatiom
batch=32
n=10
m=20
p=30

tensor1=torch.randn((batch,n,m))
tensor2=torch.randn((batch,m,p)) 
output=tensor1.bmm(tensor2)
output.size()

torch.Size([32, 10, 30])

In [61]:
#example of broadcasting
x1=torch.rand((5,5))
x2=torch.rand((1,5))
x3=x1-x2
print(x3)




tensor([[ 0.7384, -0.2076,  0.3775, -0.3414, -0.1302],
        [ 0.1728, -0.1982,  0.5911,  0.0524, -0.0906],
        [ 0.1879,  0.4550,  0.4373, -0.2663,  0.1806],
        [ 0.5199, -0.2703, -0.1429, -0.0437,  0.3103],
        [ 0.6358, -0.2488,  0.4305,  0.0230, -0.0626]])


In [62]:
print(x1*x2)

tensor([[0.0412, 0.0840, 0.2126, 0.0908, 0.0068],
        [0.0117, 0.0879, 0.2787, 0.2944, 0.0135],
        [0.0125, 0.3568, 0.2311, 0.1296, 0.0596],
        [0.0298, 0.0582, 0.0516, 0.2447, 0.0817],
        [0.0358, 0.0671, 0.2290, 0.2792, 0.0183]])


In [63]:
#---------------------Other_tensor_operation-----------------------
x=torch.tensor([[1,2,3,4],[5,6,7,8]])
y=x
print(f"Column wise sum: \n {torch.sum(x,dim=0)} ")
print(f"row wise sum \n  {torch.sum(x,dim=1)}")
value,index=torch.min(x,dim=0)
print(value)
value,index=torch.max(x,dim=1)
print(value)
index=torch.argmax(x,dim=0)
print(index)
index=torch.argmin(x,dim=1)
print(index)
print(torch.mean(x.float(),dim=0))
print(torch.eq(x,y))
value,index=torch.sort(x,dim=0,descending=True)
print(value)
print(torch.clamp(x,min=2,max=5)) #you can use it make your RELU

Column wise sum: 
 tensor([ 6,  8, 10, 12]) 
row wise sum 
  tensor([10, 26])
tensor([1, 2, 3, 4])
tensor([4, 8])
tensor([1, 1, 1, 1])
tensor([0, 0])
tensor([3., 4., 5., 6.])
tensor([[True, True, True, True],
        [True, True, True, True]])
tensor([[5, 6, 7, 8],
        [1, 2, 3, 4]])
tensor([[2, 2, 3, 4],
        [5, 5, 5, 5]])


<h1>-----------tensor_indexing-------------</h1>

In [ ]:
batch_size = 10
feature=25
z = torch.rand((batch_size,feature))

In [ ]:
print(z[0,:].shape)  # x[0,:]

torch.Size([25])


In [ ]:
#print first feature
print(z[:,0].shape)

torch.Size([10])


In [ ]:
#get 3rd ex up to 10 feature
print(z[2,0:10])

tensor([0.9003, 0.0411, 0.3458, 0.8994, 0.8810, 0.5502, 0.7342, 0.4790, 0.9703,
        0.3160])


In [ ]:
#you can assign value to the tensor
z[0,0]=100
print(z[0,0])

tensor(100.)


In [ ]:
# Fancy Indexing
x=torch.arange(10)
indices = [2,5,8]
print(x[indices])
x=torch.rand((3,5))
rows = torch.tensor([1,0])
cols=torch.tensor([4,0])
print(x[rows,cols])

tensor([2, 5, 8])
tensor([0.8499, 0.2202])


In [ ]:
# more advance indexing
x=torch.arange(10)
print(x[(x<2) | (x>8)])

tensor([0, 1, 9])


In [ ]:
print(x[x.remainder(2)==0])

tensor([0, 2, 4, 6, 8])


In [ ]:
#useful Operation
print(torch.where(x>5,x,x*2))
print(torch.tensor([0,0,1,1,2,3,3]).unique())
print(x.ndimension())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3])
1


In [ ]:
# returns total number of input tensor
print(x.numel())

10


<h1>-------------reshaping matrix--------</h1>

In [ ]:
x = torch.arange(9)
x_3x3=x.view(3,3) #need contiguous memory
print(x_3x3)
x_3x3=x.reshape(3,3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [ ]:
y=x_3x3.t()
y.flatten()

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [ ]:
x1 = torch.rand((2,5))
x2= torch.rand((2,5))
print(torch.cat((x1,x2),dim=0).shape) #vertically stack
print(torch.cat((x1,x2),dim=1).shape) #h stack

torch.Size([4, 5])
torch.Size([2, 10])


In [ ]:
batch = 64
x =  torch.rand((batch,2,5))
z =x.view(batch,-1)
print(z.shape)

torch.Size([64, 10])


In [ ]:
#switch axis while keeping batch
z= x.permute(0,2,1)
print(z.shape)

torch.Size([64, 5, 2])


In [ ]:
# torch.unsqueeze() returns a new tensor with a dimension of size one inserted at the specified position.
x = torch.arange(10)  #[0,1,2,...,9]
print(x.unsqueeze(0)) #[1,10]
print(x.unsqueeze(1))  #[10,1]

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
